paste_actions quote-urls-at-prompt

show_hyperlink_targets yes

remote_kitty if-needed

share_connections yes

mouse_map left click ungrabbed no-op

mouse_map ctrl+left click ungrabbed mouse_handle_click selection link prompt

mouse_map ctrl+left press ungrabbed mouse_selection normal

mouse_map right press ungrabbed copy_to_clipboard

modify_font cell_height 105%
font_size        10.0

background_opacity 1.0

shell_integration enabled
cursor_shape beam

cursor_blink_interval     0.3

cursor_stop_blinking_after 15.0

scrollback_lines 2000

scrollback_pager less +G -R

wheel_scroll_multiplier 5.0

click_interval 0.5

select_by_word_characters :@-./_~?&=%+#

mouse_hide_wait 60.0

enabled_layouts splits,stack
notify_on_cmd_finish invisible 10.0
visual_window_select_characters 1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ

repaint_delay    10

input_delay 3

visual_bell_duration 0.0

enable_audio_bell no

open_url_modifiers ctrl+shift
allow_hyperlinks yes

open_url_with default

term xterm-256color

window_border_width 0.5
window_margin_width 0
window_padding_width 0.0
draw_minimal_borders yes

tab_bar_style powerline
tab_powerline_style slanted
tab_fade 0.25 0.5 0.75 1

map super+v             paste_from_clipboard
map ctrl+shift+s        paste_from_selection
map super+c             copy_to_clipboard
map shift+insert        paste_from_selection

map ctrl+shift+up        scroll_line_up
map ctrl+shift+down      scroll_line_down
map ctrl+shift+k         scroll_line_up
map ctrl+shift+j         scroll_line_down
map ctrl+shift+page_up   scroll_page_up
map ctrl+shift+page_down scroll_page_down
map ctrl+shift+home      scroll_home
map ctrl+shift+end       scroll_end
map ctrl+shift+h         show_scrollback

map super+n             new_os_window
map super+w             close_window
map ctrl+shift+enter    new_window
map ctrl+up             next_window
map ctrl+down           previous_window
map ctrl+shift+f        move_window_forward
map ctrl+shift+b        move_window_backward
map ctrl+shift+`        move_window_to_top
map ctrl+shift+1        first_window
map ctrl+shift+2        second_window
map ctrl+shift+3        third_window
map ctrl+shift+4        fourth_window
map ctrl+shift+5        fifth_window
map ctrl+shift+6        sixth_window
map ctrl+shift+7        seventh_window
map ctrl+shift+8        eighth_window
map ctrl+shift+9        ninth_window
map ctrl+shift+0        tenth_window

map ctrl+shift+right    next_tab
map ctrl+shift+left     previous_tab
map ctrl+shift+t        new_tab
map ctrl+shift+q        close_tab
map ctrl+shift+l        next_layout
map ctrl+shift+.        move_tab_forward
map ctrl+shift+,        move_tab_backward

map ctrl+shift+backspace restore_font_size

hide_window_decorations yes
macos_option_as_alt no

allow_remote_control yes

include current-theme.conf

font_family      family='Hack Nerd Font' style=Italic
