[manager]
show_hidden = false
sort_by = "natural"
sort_dir_first = true

[prefetch]
tasks = 5

[opener]
edit = [
  { run = 'nvim "$@"', block = true },
]

[open]
rules = [
  { name = "*.md", use = "edit" },
  { name = "*.txt", use = "edit" },
]
