;udio]==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

; dracula colorscheme
[colors]
background = #282a36
background-alt = #44475a
foreground = #f8f8f2
primary = #bd93f9
secondary = #ffb86c
alert = #ff5555
disabled = #6272a4

[bar/i3bar]
width = 100%
height = 18pt
line-size = 2pt
padding-right = 2
background = ${colors.background}
foreground = ${colors.foreground}

; set font to Hack Nerd Font
font-0 = "Hack Nerd Font:style=Regular:size=8"
; set font to FiraCode for icons
font-1 = "FiraCode Nerd Font:style=Regular:size=8"

modules-left = ewmh memory cpu
modules-center = chrome gedit mail file
modules-right = network pulseaudio date tray powermenu

; Adds spacing between modules
module-margin = 1

cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

; All Left side tabs
; Workspaces tab
[module/ewmh]
type = internal/xworkspaces

;; icon-[0-9]+ = <desktop-name>;<icon>
; Map desktop names to some icon. The icon is then available in the %icon% token
; ; NOTE: The desktop name needs to match the name configured by the WM
; ; You can get a list of the defined desktop names using:
; ; $ xprop -root _NET_DESKTOP_NAMES
; ; NOTE: Neither <desktop-name> nor <icon> can contain a semicolon (;)
;
icon-0 = 1
icon-1 = 2
icon-2 = 3
icon-3 = 4
icon-4 = 5

; Used for the currently selected workspace
label-active = %name%
label-active-foreground = ${colors.foreground}
label-active-background = ${colors.background-alt}
label-active-underline = ${colors.primary}
label-active-padding = 2

; Used for workspace at least one window
label-occupied = %name%
; label-occupied-underline = ${colors.primary}
label-occupied-padding = 2

; Used for workspaces containing a window that is demanding attention
label-urgent = %name%
label-urgent-foreground = ${colors.foreground}
label-urgent-background = ${colors.alert}
label-urgent-padding = 2

; Used for workspaces without windows
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 2

[module/memory]
type = internal/memory

; Seconds to sleep between updates
interval = 5
warn-percentage = 95
label = " %percentage_used%%"
format-prefix-foreground = ${colors.primary}
label-padding = 1

[module/cpu]
type = internal/cpu

; Seconds to sleep between updates
interval = 0.5
warn-percentage = 95
label = " %percentage:2%%"
format-prefix-foreground = ${colors.primary}
label-padding = 1

; Center tabs
[module/xwindow]
type = internal/xwindow
label = %title%
label-maxlen = 50

; Right tabs
[module/pulseaudio]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>
label-volume = %percentage%%

format-muted = <label-muted>
label-muted =  muted
label-muted-foreground = ${colors.disabled}

format-headphones = 󰋋 <label-volume>
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

click-middle = pactl set-sink-mute @DEFAULT_SINK@ toggle
click-right = pavucontrol

[module/network]
type = internal/network
interface-type = wired
interval = 5
label = "%local_ip%"
label-connected = "󰖩 %netspeed%"
label-disconnected = "󰖪 Disconnected"
label-foreground = ${colors.foregound}
label-padding = 2

[module/date]
type = internal/date
interval = 1.00
date = "%a %b %d"
time = %H:%M
; Nice way on enabling on-click behavior 
label = "%{A1:gnome-calendar:} %date% %time%%{A}"
; label-background = ${colors.background-alt}
label-padding = 2

[module/tray]
type = internal/tray
background = ${colors.background}
tray-maxsize = 24

[module/powermenu]
type = custom/text

content = ""
content-foreground = ${colors.alert}

click-left = ~/.config/polybar/scripts/powermenu.sh


; type = custom/menu
; expand-right = true
; format-spacing = 1
;
; label-open = ""
; label-open-foreground = ${colors.alert}
; label-close =  cancel
; label-close-foreground = ${colors.primary}
; label-separator = |
; label-separator-foreground = ${colors.foreground}
;
; ; Powermenu
; menu-0-0 = "Reboot "
; menu-0-0-exec = menu-open-1
; menu-0-0-foreground = ${colors.alert}
;
; menu-0-1 = "Power Off"
; menu-0-1-exec = menu-open-2
; menu-0-1-foreground = ${colors.alert}
;
; menu-0-2 = "Suspend"
; menu-0-2-exec = menu-open-3
; menu-0-2-foreground = ${colors.secondary}
;
; ; Reboot
; menu-1-0 = "Cancel "
; menu-1-0-exec = menu-open-0
; menu-1-0-foreground = ${colors.primary}
; menu-1-1 = "Reboot"
; menu-1-1-exec = systemctl reboot
; menu-1-1-foreground = ${colors.alert}
;
; ; Shutdown
; menu-2-0 = "Power off"
; menu-2-0-exec = systemctl poweroff
; menu-2-0-foreground = ${colors.alert}
; menu-2-1 = "Cancel "
; menu-2-1-exec = menu-open-0
; menu-2-1-foreground = ${colors.primary}
;
; ; Hibernate
; menu-3-0 = "Suspend"
; menu-3-0-exec = systemctl suspend
; menu-3-0-foreground = ${colors.alert}
; menu-3-1 = "Cancel"
; menu-3-1-exec = menu-open-0
; menu-3-1-foreground = ${colors.primary}
;
; center user modules
[module/chrome]
type = custom/text
click-left = google-chrome &
content = " "

[module/gedit]
type = custom/text
click-left = gedit &
content = "󱚌 "

[module/mail]
type = custom/text
click-left = thunderbird &
content = "󰇮 "

[module/file]
type = custom/text
click-left = nautilus &
content = " "

